package se.pbt.sudokusolver.core.generation.helpers;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import se.pbt.sudokusolver.core.generation.SudokuBuilder;
import se.pbt.sudokusolver.core.models.SudokuBoard;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("UniquenessChecker")
class UniquenessCheckerTest {

    @Test
    @DisplayName("returns true for a fully solved 4x4 board")
    void hasUniqueSolution_returnsTrue_forSolved4x4Board() {
        SudokuBoard board = createSolved4x4Board();
        UniquenessChecker checker = new UniquenessChecker();

        boolean unique = checker.hasUniqueSolution(board);

        assertTrue(unique, "Expected solved 4x4 board to have a unique solution");
    }

    @Test
    @DisplayName("does not modify original board when checking uniqueness")
    void hasUniqueSolution_doesNotModifyOriginalBoard() {
        SudokuBoard board = createSolved4x4Board();
        SudokuBoard snapshot = board.deepCopy();
        UniquenessChecker checker = new UniquenessChecker();

        checker.hasUniqueSolution(board);

        assertBoardsEqual(snapshot, board);
    }

    @Test
    @DisplayName("returns true for solution board generated by SudokuBuilder")
    void hasUniqueSolution_returnsTrue_forSolutionBoardFromBuilder() {
        int size = 4;
        double clueFraction = 0.5;

        SudokuBuilder builder = new SudokuBuilder(new UniquenessChecker(), new SolutionGenerator());

        SudokuBoard playable = builder.buildPlayableBoard(size, clueFraction);
        SudokuBoard solution = builder.getSolutionBoard();

        assertNotNull(playable);
        assertNotNull(solution);

        UniquenessChecker checker = new UniquenessChecker();
        boolean unique = checker.hasUniqueSolution(solution);

        assertTrue(unique, "Expected solution board from builder to have a unique solution");
    }


    /**
     * Builds a fixed, fully solved 4x4 Sudoku board used as a deterministic test fixture.
     */
    private SudokuBoard createSolved4x4Board() {
        int[][] solved = {
                {1, 2, 3, 4},
                {3, 4, 1, 2},
                {2, 1, 4, 3},
                {4, 3, 2, 1}
        };
        SudokuBoard board = new SudokuBoard(4);
        for (int row = 0; row < solved.length; row++) {
            for (int col = 0; col < solved[row].length; col++) {
                board.setValue(row, col, solved[row][col]);
            }
        }
        return board;
    }

    /**
     * Asserts that two boards have the same size and identical values in all cells.
     */
    private void assertBoardsEqual(SudokuBoard expected, SudokuBoard actual) {
        assertEquals(expected.getRowLength(), actual.getRowLength(), "Board sizes must match");
        int size = expected.getRowLength();
        for (int row = 0; row < size; row++) {
            for (int col = 0; col < size; col++) {
                assertEquals(expected.getCellValue(row, col), actual.getCellValue(row, col),
                        "Boards differ at (" + row + "," + col + ")");
            }
        }
    }

}
